### ISSUE TITLE
Add/removing classes not working properly

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-hiding-navigation-changelog#1]
Hi CodyHouse Team,

as i allready meantioned in a private message, here again:
The adding or removing of the .hide-nav--off-canvas class is not working properly

Please have a look at our project. The page is hide for public, so please use the htaccess Login:
http://www.mailingwork.de.web04.w3work-test.de/

User: mailingwork
PW: mw!relaunch

When you scroll down the page, you see the header gets fixed and the box-shadow is added. After i while scrolling the header gets hide and also box-shadow removes. All correct here.
But now scroll a little bit back to top, so that Header gets visible again. As you can see, the box-shadow pops up short and then gets removed again. This happens, when you scroll back to top and stop the scrolling immediatelyafter header gets visible.
If you then move on the scrolling to top, the box-shadow (or the .hide-nav--off-canvas class) gets visible again - but only if you scroll a little bit faster. If you scroll just one-step of the mouse wheel, the box-shadow will still get hide.

Regards
Sven

**Comment by claudia-romano** [comment]
Hi Sven, thanks for the heads-up. We just pushed a new version of the Hiding Nav component that should fix the issue. Cheers.

**Comment by w3work** [comment]
Hi Claudio,
the issues is fixed. Thank you very much for this quick response! Really great support here.

Addional question:
The .hide-nav--off-canvas class is not added on mobile menu, right? Because here it is for example not working with the box-shadow i set.

**Comment by claudia-romano** [comment]
Hi there,
the .hide-nav--off-canvas class is added to the mobile menu as well. 
Please make sure the box-shadow issue is not related to some custom style (you can check the class is added using the console). Cheers.
